### ISSUE TITLE
[Bug] Metadata/Frontmatter Tags Don't Show Text

### ISSUE THREAD

**Issue by SlRvb** [ZaherAlMajed/Illusion-Theme.md#1]
![EmjbTA4s89](https://user-images.githubusercontent.com/54087190/125832347-10009d98-54c0-496d-a959-6f6c85062d56.gif)

It seems like your `--text-normal` color matches the color of the frontmatter tag bubbles.

Something like this could help:
```css
.frontmatter-container .tag { color: var(--Color-White-Page); }
.frontmatter-container .tag:hover { color: var(--text-normal); }
.frontmatter-container .frontmatter-alias { color: unset; }
```
![tuMGPR3EyB](https://user-images.githubusercontent.com/54087190/125835731-ece245a0-4353-4634-9a97-9c2a2170b128.gif)
